[providers.age]
type = "age"
recipients = [
  "age1fgs45gewp9z6uz20mkvmy4xypvwen9wnjhhhgjcsl0cy0pq3qqgs4vdpd7",
  "age1d4mduua39qk35huml983efwq2q9p5ufve9gwkzfk5al4k5r05qgshan69q",
]

[secrets]
ENV= { default = "local" }
DATABASE_URL= { default = "postgresql://postgres:password@localhost:4718/k2c_agents?sslmode=disable" }
OPENAI_AGENTS_DISABLE_TRACING= { default = "1" }
S3_ENDPOINT= { default = "http://localhost:4900" }
S3_ACCESS_KEY= { default = "minioadmin" }
S3_SECRET_KEY= { default = "minioadmin" }
S3_BUCKET= { default = "k2c-agents" }
S3_REGION= { default = "us-east-1" }
AGENT_INTERVAL_SECONDS= { default = "20" }
CONFIG_API_BASE_URL= { default = "http://localhost:8001" }
LEAD_API_BASE_URL= { default = "http://localhost:8002" }
LEAD_SERVER_PORT= { default = "8002" }
LOG_LEVEL= { default = "DEBUG" }
OPENAI_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZVBCczZxNFA4WDJNUDNwRS95TDN3cDE3c3dHMlRwYjNqMW0zN1FUWFJNCnR5czlkb1dETXBzSUxyMzBGelZtSVoyRTBrUVc2ZHAybGJiZW5jcEtpQmMKLT4gWDI1NTE5IFdvYmFKdEZQYzVoNC9EWjJHUHBkclBmVU5teU5OYWpVMnZVMnppZkpHVVkKa3F4eUpDdUdlNDh3MUhxVDNZT2xwdDh2RXVVd0V2bkN6U3hRNEIrSGNvWQotPiAzQUdaNEQtZ3JlYXNlIFpiaidqYSA3CkV2eWNHSzkrRXg5dFJac0dBMWE0MzNaa1lXRyt2MmhvYkdJOEJvYUZKaDdnR3pBeE9MWjU4cUhiaCt4SFdYL2QKakVUKzZQNEU1YTBHcXRKaGJUdm03T1lZc3JDNGc1QUJuNS83Q0dNekNBUDM2STdRTXcKLS0tIGFNOWtHem1hNjhZU09SRUhQZVp5QWxMbG1qQWs5djJ2RjVkb1JOa0k0Q28KCyWueUTx0hWEsDNsZVCdxZE2qrJ/TgdSGLwJoHDM62fZ2f0mejbqZ/UZlz6dAdIS1NdgKpQgZyv6a3GHF4cmPLc+or8VAG3DCZ+WXAmAAPdNio8ISXp1GdyYdbMdGiLfgZRvbW0dCckEzqMVk6clsIdVz8c0chgEDVp2UtWlXOzwvqDU3gmBfj43YLk+Ir+l+Zc3g16i+JJTPYXEM0jJsenJ8l4pVPY0616Nm1D3Y1TIjqQkIHGXeWqI4hxYaz7YEZDX8A==" }
OPENAI_MODEL= { default = "gpt-5.2" }
OPENROUTER_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTWxVVElHLzA1MWxEMzhrT0hmUEVHcU5ZRFpOUzVMQzVSbWpmYzRXdjJRCk5OUGN6a3lCbm5zR01xSFBRL0oyeGZzbEJLOGNFK0pJTW9hQjNjYS9Lck0KLT4gWDI1NTE5IDlNV01BamZleUdPM081SWxza083MytNVjkxdHZpZmhkSkxNQUpTS1FPV1UKNEZKeXRnYmlxK1ZWZFo2Ulk0REVRL2xPMVdvNDBJY1BBZEJNOXppL3lkYwotPiBtfHktZ3JlYXNlID5fMmhpeVkgPXRWIERWKVkucycKV1hMaUlPNFJTNzJTb0xoYzlSa1Nnb245aFltMmo5a3NoWXVNSE9nQW9kcXNTS2JOaTRGb2R0YUNxaWVLcUhtNgptdTJFRHM1ZEVUQytpbkVrcUpleU44RVZYOUkweVFWZnRNQjluQSszVUNobDR3Ci0tLSBPSzZ0dkZyeFFNOGRBWWFELzhJSTlvZ2xDWXBnRGNwUUhTZDVqR0xWYXJNCn/kAksy+su+fuzm1OKND9l6BaM0EBye9NCX9V2Y/qPvsIA7bkcBKLE/E/vwSUf8aKxukqBfVz+ce0IP925lnqSIugy3lPn6QhSzl3hPGjGZsB08pdUOQgOzbPyCX/HQkClUN5g58HXSPg==" }
