[providers.age]
type = "age"
recipients = [
    "age1fgs45gewp9z6uz20mkvmy4xypvwen9wnjhhhgjcsl0cy0pq3qqgs4vdpd7",
    "age1d4mduua39qk35huml983efwq2q9p5ufve9gwkzfk5al4k5r05qgshan69q",
    "age133ct79t3vrsxp5f8au60gsgztvxjg85azu6mxals205am8c58eeq4qt9ax",
]

[secrets]
# k2c-agents
ENV= { default = "local" }
DATABASE_URL= { default = "postgresql://postgres:password@localhost:4718/k2c_agents?sslmode=disable" }
OPENAI_AGENTS_DISABLE_TRACING= { default = "1" }
S3_ENDPOINT= { default = "http://localhost:4900" }
S3_ACCESS_KEY= { default = "minioadmin" }
S3_SECRET_KEY= { default = "minioadmin" }
S3_BUCKET= { default = "k2c-agents" }
S3_REGION= { default = "us-east-1" }
AGENT_INTERVAL_SECONDS= { default = "20" }
OPENAI_MODEL= { default = "gpt-5.2" }
OPENAI_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZGpSN0ZDU2g4TDZVZGZHYVc0THJBRHNHNW45OUk2dUJ2SERMZE13N1JFCmFmMktZYTlvbXhlOVNINXRHSzU4cmVRRldWZm1RZWFTVkh4QW1ZZy8raG8KLT4gWDI1NTE5IHNaUStneEY1Sm1JOWJtZUxVMEQ2YmhpSG5lK1pCcEpqNnloUHhhRTJxUm8KcmViaXdPWS9aVjlPQ3RZa1BKY2FMZEVLZ3ZkUkRtMHlQRDhGWEtBK1pvYwotPiBYMjU1MTkgMUxuM3BVUzdJakJzeGpKOGMvR2VhY0NsM1VIMzBrUkRUN2IraHJiUy95dwo0OGVVcFFCcHhpdWFJMUtyaHg2Y2tOSUFCMC9EaVhnWFVZblR5eVNheGI4Ci0+ICV5fkFCRC1ncmVhc2UgdylediVkbCBQIHFTdCBQbwo5ejNPaVBqOXlSVDlOby80MFhCSWdRCi0tLSBpYkE3SlFsRGpoYjd3WnRwYkUvMEJJM2Zvb2Z4ZFBwOU5keVJjWE0zODRVCgRqKh2BDZ85bVbRkogci/C7Rfn44XVobyTZsX7o66JtA/cypKnux7cN2e05GJqQR/ja+rvKMY20bCeJRNx4VgAbQITpJJJZquefiPzP17tblVuXr3E6nVSj46xrGqkd1M5b4JHa7lB73KOBzr9mfujRoJ16RrbNTXJ2tkBqBcADomswqB8wHrvK1kbo6/MuFjzF662M08LrjNHeu5qEZYNSrsB0FeDHBnZef8853gOxr++XD87a7mb6dXk1JrCdxToFfu4=" }
OPENROUTER_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTTF3UG1QWWphRzFxWlJZYWttSGFqbnlFQkxiNk1hZ2xRT2dYWGgvRjBRCm03SDUyNVlYdkZONzYwQmNlNHBjeG5wQlJNUUxuR3RlU1l4bnJ6K0hZYmcKLT4gWDI1NTE5IEk1QnQ3bnV2SzlUQXdyS1pGSzZVSXp6MTVjbEg3VjhYeHB4T2pHVU4wMVUKQW0zdTZYT3RnNWo0cFA5NmVyQjljZmV3VWpSL1htTjlUNno2eHVBZWtkZwotPiBYMjU1MTkgUk02QzdrbDllVjE4S3E5ZEtLdUh4WlF6YkwxUDhuNXhWcG9Hd3pqZkwwTQo4OXM5YWZ2eUZWelk2NmlNcmFqcW8zTUdjQmVBeFZweUtndFZQT2ZwcmF3Ci0+IDMyWFd5LWdyZWFzZSAhYn0gWTYyfTlrKUkgSEJbYSNLQgpTaHZ1VG55UFQ3KzNoSVo5Z1BQL3VnUVJGWUlFNlFJOERMN3NNb2pJcWhtQzVLMDhNakxVWmFkbkRtbWpoQm1HCgotLS0gNmJ2SEZXdUw1eFZ6WnEzVml5K2FnNUxNSkFlQ1dHQmZxYmxodURYdXJmUQrI43kva2874keCNVJR3kY+FNKGCgaJInDHMsemeEf8XdA20aS7yliecyOqRPunkN7ORhvwcVXz6Frrizzvx2VuOCXsAuFTQ1tFR0QFseBf13QIYFDo8fIxdaIhfFeoDoZZGb5F53C2WT4=" }
# k2c-collector
API_ENDPOINT= { default = "http://localhost:8000/upload" }
CAPTURE_INTERVAL_SECONDS= { default = "10" }
IMAGE_FORMAT= { default = "png" }
IMAGE_QUALITY= { default = "100" }
