[providers.age]
type = "age"
recipients = [
  "age1fgs45gewp9z6uz20mkvmy4xypvwen9wnjhhhgjcsl0cy0pq3qqgs4vdpd7",
  "age1d4mduua39qk35huml983efwq2q9p5ufve9gwkzfk5al4k5r05qgshan69q",
]

[secrets]
ENV= { default = "local" }
DATABASE_URL= { default = "postgresql://postgres:password@localhost:4718/k2c_agents?sslmode=disable" }
OPENAI_AGENTS_DISABLE_TRACING= { default = "1" }
S3_ENDPOINT= { default = "http://localhost:4900" }
S3_ACCESS_KEY= { default = "minioadmin" }
S3_SECRET_KEY= { default = "minioadmin" }
S3_BUCKET= { default = "k2c-agents" }
S3_REGION= { default = "us-east-1" }
AGENT_INTERVAL_SECONDS= { default = "20" }
OPENAI_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMjI1MVN5M2k0OTkxR3F0RFl4eU80RVlhVklISUI1L3UrTG41bkNOTld3CkwzcVozRWF2NVFGbHhzaEhuL0liZlpBRUpSdUF6M0toSmtJN0FMQ2YxaGcKLT4gWDI1NTE5IEF0MWRmUzdOUkJSUjNRQlVJaDhGYU1TQ2V4MXVGUkxqa3hzcVA5NjBMWDQKZUZLekVLYUQxaElRcnptSndSS1YyZFo2eDN4NHJabmFkbE5udy9CVFR2QQotPiAvL3ckNSRaTy1ncmVhc2Ugdl9fXGJ2ID1zIXouLXMrIF1QXS1hb2AgcCJyQ3F7TApSZDB4N2svWmxxcGU2VjR1QTNLNThKOURrL1lTeUhCWmcwbjVzcmR5cVpjSGs3bjlRS3BibWxhKzBlRFRXdUUwCktnSHJaOEdYdmlSUWlwM3JmazRjYVEKLS0tIG1HdDVRMytxRXZuUDg5bmhlYWdZNDN0MEU3R3k1WlZXajlGWmZYV21xWlkK52kDg2h/DFQAzDfbYhvQe/QStOxXco49iuNGhKtui/WnExatwjZhk9zSXwRh+HZdUYJh1dIzRP3f31kHeHmLYZaqxNRluGDRgn4K0yIFXoAJP3pjJHP9t/x3A+ExvkfwrAeQvGQBgYDyZXiUtyY5dJaOtWioZatBjUVOWMDOs8LaAD8SzY/8OCo0u8/yBSvKw8HGEOFi2n8vf9FlvWHUsZ583Rzr7SApWF9TYahir3bPkA2PrUvqrZDw/Bwwqxa2byu4yg==" }
OPENROUTER_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTWxVVElHLzA1MWxEMzhrT0hmUEVHcU5ZRFpOUzVMQzVSbWpmYzRXdjJRCk5OUGN6a3lCbm5zR01xSFBRL0oyeGZzbEJLOGNFK0pJTW9hQjNjYS9Lck0KLT4gWDI1NTE5IDlNV01BamZleUdPM081SWxza083MytNVjkxdHZpZmhkSkxNQUpTS1FPV1UKNEZKeXRnYmlxK1ZWZFo2Ulk0REVRL2xPMVdvNDBJY1BBZEJNOXppL3lkYwotPiBtfHktZ3JlYXNlID5fMmhpeVkgPXRWIERWKVkucycKV1hMaUlPNFJTNzJTb0xoYzlSa1Nnb245aFltMmo5a3NoWXVNSE9nQW9kcXNTS2JOaTRGb2R0YUNxaWVLcUhtNgptdTJFRHM1ZEVUQytpbkVrcUpleU44RVZYOUkweVFWZnRNQjluQSszVUNobDR3Ci0tLSBPSzZ0dkZyeFFNOGRBWWFELzhJSTlvZ2xDWXBnRGNwUUhTZDVqR0xWYXJNCn/kAksy+su+fuzm1OKND9l6BaM0EBye9NCX9V2Y/qPvsIA7bkcBKLE/E/vwSUf8aKxukqBfVz+ce0IP925lnqSIugy3lPn6QhSzl3hPGjGZsB08pdUOQgOzbPyCX/HQkClUN5g58HXSPg==" }
